version: '3.4'
services:
    data_worker:
        image: notchristiangarcia/data_worker
        env_file: "worker_vars.env"

    graph_worker:
        image: notchristiangarcia/graph_worker
        env_file: "worker_vars.env"

    stats_worker:
        image: notchristiangarcia/stats_worker
        env_file: "worker_vars.env"
