version: '3.4'
services:
    graph_worker:
        build:
            context: ../../../
            dockerfile: ./docker/graph_worker/Dockerfile
        image: notchristiangarcia/graph_worker
        env_file: "worker_vars.env"
