version: '3.4'
services:
    redis:
        image: redis:alpine
        ports:
         - "6379:6379"
        environment:
         - "REDIS_URL=redis://redis_db:6379"

    api:
        image: notchristiangarcia/api_image
        ports:
         - "5000:5000"
        env_file: "env_vars.env"
