version: '3.4'
services:
    redis:
        image: redis:alpine
        ports:
         - "6379:6379"

    api:
        image: notchristiangarcia/api_image
        ports:
         - "5000:5000"
        env_file: "env_vars.env"
        
    data_worker:
        image: notchristiangarcia/data_worker
        env_file: "env_vars.env"

    graph_worker:
        image: notchristiangarcia/graph_worker
        env_file: "env_vars.env"

    stats_worker:
        image: notchristiangarcia/stats_worker
        env_file: "env_vars.env"
